
- task: UsePythonVersion@0


  inputs:


    versionSpec: '$(python.version)'


  displayName: 'Use Python $(python.version)'


- script: python "lab1a.py"



- task: PythonScript@0


  inputs:


    scriptSource: 'inline'


    script: |


      print('Hello world 1')


      print('KLU')